name: CI/CD Pipeline

on:
  push:
    branches:
      - v2

jobs:
  # Stage 1: Checkout and Setup
  setup:
    name: Checkout and Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

  # Stage 2: Terraform Validation
  validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    needs: setup  # Виконується після setup

    steps:
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check

  # Stage 3: Linting and Security Checks
  lint_security:
    name: Linting and Security Checks
    runs-on: ubuntu-latest
    needs: validate  # Виконується після validate

    steps:
      # tflint Check
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        run: tflint --init && tflint

      # checkov Check
      - name: Install checkov
        run: pip install checkov

      - name: Run checkov
        run: checkov -d .


  