name: Terraform Deploy

on:
  push:
    branches:
      - main  # Запускає пайплайн при кожному пуші в основну гілку
  pull_request:
    branches:
      - main  # Запускає пайплайн при кожному pull request до основної гілки

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Вкажіть версію Terraform, яку ви використовуєте

      - name: Terraform Init
        run: |
          cd environments/dev  # Перейдіть до каталогу середовища
          terraform init

      - name: Terraform Plan
        run: |
          cd environments/dev  # Перейдіть до каталогу середовища
          terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd environments/dev  # Перейдіть до каталогу середовища
          terraform apply -auto-approve tfplan
